export const BANNER_TOUCH_AVATAR = 'BANNER_TOUCH_AVATAR';
export const BANNER_UNTOUCH_AVATAR = 'BANNER_UNTOUCH_AVATAR';
export const ON_RESIZE_WINDOW = 'ON_RESIZE_WINDOW';
export const ON_MOUSE_MOVE = 'ON_MOUSE_MOVE';
export const ON_TOUCH_MOVE = 'ON_TOUCH_MOVE';